FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY app/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container
COPY . .

# Define the command to run Celery
CMD ["celery", "-A", "app.celery_worker.celery worker" "--loglevel=info"]