FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY app/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container
COPY . .

# Expose the port that Flask runs on
EXPOSE 5000

# Define the command to run Flask
CMD ["gunicorn", "-b", "0.0.0.0:5000" "app:app"]